[[redirects]]
  from = "/yandex/search"
  to = "https://api.music.yandex.net/search"
  status = 200
  force = true
  headers = {Host = "api.music.yandex.net"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"