[[redirects]]
  from = "https://tangerine-zuccutto-452844.netlify.app/yandex/*"
  to = "https://api.music.yandex.net/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}